project_id = "edctpsdcrivpxynfxpef"

[functions.fetch-sheets-data]
verify_jwt = false

[functions.fetch-financial-data]
verify_jwt = false

[functions.start-google-oauth]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false
