project_id = "edctpsdcrivpxynfxpef"

[functions.fetch-sheets-data]
verify_jwt = false

[functions.fetch-financial-data]
verify_jwt = false

[functions.start-google-oauth]
verify_jwt = false

[functions.google-oauth-callback]
verify_jwt = false

[functions.voip-webhook-api4com]
verify_jwt = false

[functions.transcribe-call-recording]
verify_jwt = false

[functions.voip-webhook-3cplus]
verify_jwt = false

[functions.play-3cplus-recording]
verify_jwt = false

[functions.recheck-3cplus-recordings]
verify_jwt = false
