
ALTER TABLE public.crm_projetos
  ADD COLUMN IF NOT EXISTS escopo_trafego BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS escopo_social_media BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS escopo_design BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS escopo_crm BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS escopo_validado BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS escopo_validado_em TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS escopo_validado_por UUID,
  ADD COLUMN IF NOT EXISTS escopo_ia_sugestao JSONB,
  ADD COLUMN IF NOT EXISTS escopo_ia_gerado_em TIMESTAMPTZ;
